# Generated by Django 4.1.3 on 2023-03-31 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('subject', models.CharField(max_length=128)),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='nr_matricol',
            field=models.CharField(max_length=64),
        ),
    ]
